name: Build and release

on:
  push:
    branches:
      - ci

jobs:
  BuildAndRelease:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        run: pip install poetry

      - name: Setup poetry
        run: poetry config virtualenvs.in-project true

      - name: List poetry config
        run: poetry config --list

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry run invoke build
